# Generated by Django 4.2.3 on 2023-07-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('views', models.BigIntegerField()),
                ('subscribers', models.IntegerField()),
                ('video_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('likes', models.IntegerField()),
                ('replies', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.video')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='most_likes_videos',
            field=models.ManyToManyField(related_name='most_likes_videos', to='app.video'),
        ),
        migrations.AddField(
            model_name='channel',
            name='most_viewed_videos',
            field=models.ManyToManyField(related_name='most_viewed_videos', to='app.video'),
        ),
    ]
