# Generated by Django 4.2.3 on 2023-07-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_historicalvideo_historicalcomment_historicalchannel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalComment',
        ),
    ]
